@host = http://localhost:8080
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzY29yZXRyYWNrciIsInN1YiI6InJhbnNlbGxAZ21haWwuY29tIiwiaWQiOiJkNWUyZDY0YS1kZmI3LTExZWMtOWQ2NC0wMjQyYWMxMjAwMDIiLCJhdXRob3JpdGllcyI6IkFETUlOIiwiZXhwIjoxNjU1NjU4MjI3fQ.aE15bGd-8lZ49PFUAxLRAXKfJ3RmrDN_Q-OlL_Ma24Q

### --- USER HTTP REQUESTS --- ###

### CREATE USER JOHN SMITH
POST {{host}}/user/create HTTP/1.1
Content-Type: application/json

{
    "userId": "7b95dbea-dfbe-11ec-9d64-0242ac120002",
    "email": "jsmith@gmail.com",
    "password": "JSmithPassword1!",
    "confirmPassword": "JSmithPassword1!",
    "first_name": "John",
    "last_name": "Smith",
    "handicap": 1
}

### LOGIN jsmith@gmail.com
POST {{host}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "email": "jsmith@gmail.com",
    "password": "JSmithPassword1!"
}

### LOGIN ADMIN (ransell@gmail.com)
POST {{host}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "email": "ransell@gmail.com",
    "password": "ehCX7MexUCb&T7"
}

### GET ALL ROLES
GET {{host}}/user/role HTTP/1.1

### GET BY USER ID d5e2d64a-dfb7-11ec-9d64-0242ac120002 
GET {{host}}/user/d5e2d64a-dfb7-11ec-9d64-0242ac120002 HTTP/1.1

### GET BY EMAIL "ransell@gmail.com"
GET {{host}}/user/email/ransell@gmail.com HTTP/1.1

### GET BY FIRST NAME "Ryan"
GET {{host}}/user/firstName/Ryan HTTP/1.1

### GET BY LAST NAME "Ansell"
GET {{host}}/user/lastName/Ansell HTTP/1.1

### CHANGE JOHN SMITH'S HANDICAP

PUT {{host}}/user/update HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}}

{
    "email": "jsmith@gmail.com",
    "password": "JSmithPassword1!",
    "first_name": "Johnny",
    "last_name": "Smith",
    "handicap": 2
}






### --- COURSE HTTP REQUESTS --- ###

### GET ALL COURSES
GET {{host}}/scoretrackr/course HTTP/1.1

### GET COURSE BY ID 79c2efca-dfb8-11ec-9d64-0242ac120002
GET {{host}}/scoretrackr/course/79c2efca-dfb8-11ec-9d64-0242ac120002 HTTP/1.1

### GET COURSE BY NAME "Fox Run Golf Club"
GET {{host}}/scoretrackr/course/name/Fox%20Run%20Golf%20Club HTTP/1.1

### CREATE COURSE HILAMAN
POST {{host}}/scoretrackr/course HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}}

{
    "courseId": "fd844c1e-dfcc-11ec-9d64-0242ac120002",
    "name": "Hilaman Golf Course",
    "address": "2737 N Blair Stone Rd",
    "city": "Tallahassee",
    "state": "FL",
    "zipCode": "32301",
    "phoneNumber": "(850) 891-2560",
    "email": "admin@scoretrackr.com",
    "rating": 90.0,
    "slope": 115.0
}

### CHANGE HILAMAN'S EMAIL
PUT {{host}}/scoretrackr/course/fd844c1e-dfcc-11ec-9d64-0242ac120002 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}}

{
    "courseId": "fd844c1e-dfcc-11ec-9d64-0242ac120002",
    "name": "Hilaman Golf Course",
    "address": "2737 N Blair Stone Rd",
    "city": "Tallahassee",
    "state": "FL",
    "zipCode": "32301",
    "phoneNumber": "(850) 891-2560",
    "email": "adminUpdated@scoretrackr.com",
    "rating": 90.0,
    "slope": 115.0
}






### --- HOLE HTTP REQUESTS --- ###

### GET BY HOLE ID 83238746-dfb8-11ec-9d64-0242ac120002
GET {{host}}/scoretrackr/hole/holeId/83238746-dfb8-11ec-9d64-0242ac120002 HTTP/1.1

### GET BY NINE ID 7cd3871a-dfb8-11ec-9d64-0242ac120002
GET {{host}}/scoretrackr/hole/nineId/7cd3871a-dfb8-11ec-9d64-0242ac120002 HTTP/1.1

### CREATE HOLE W/ ID:  f9c91d92-dfcd-11ec-9d64-0242ac120002 AT FOX RUN YARDS
POST {{host}}/scoretrackr/hole HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}}

{
    "holeId": "f9c91d92-dfcd-11ec-9d64-0242ac120002",
    "number": 10,
    "handicap": 7,
    "par": 5,
    "yards": 200,
    "nine": {
        "nineId": "7cd3871a-dfb8-11ec-9d64-0242ac120002",
        "name": "Front 9",
        "course": {
            "courseId": "79c2efca-dfb8-11ec-9d64-0242ac120002",
            "name": "Fox Run Golf Club",
            "address": "129 County Hwy 142A",
            "city": "Johnstown",
            "state": "NY",
            "zipCode": "12095",
            "phoneNumber": "(518)-762-3717",
            "email": "richardscott@pga.com",
            "rating": 70.0,
            "slope": 125.0
        }
    }
}

### CHANGE HOLE W/ ID:  f9c91d92-dfcd-11ec-9d64-0242ac120002 AT FOX RUN YARDS
PUT {{host}}/scoretrackr/hole/19 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}}

{
    "holeId": "f9c91d92-dfcd-11ec-9d64-0242ac120002",
    "number": 10,
    "handicap": 7,
    "par": 5,
    "yards": 400,
    "nine": {
        "nineId": "7cd3871a-dfb8-11ec-9d64-0242ac120002",
        "name": "Front 9",
        "course": {
            "courseId": "79c2efca-dfb8-11ec-9d64-0242ac120002",
            "name": "Fox Run Golf Club",
            "address": "129 County Hwy 142A",
            "city": "Johnstown",
            "state": "NY",
            "zipCode": "12095",
            "phoneNumber": "(518)-762-3717",
            "email": "richardscott@pga.com",
            "rating": 70.0,
            "slope": 125.0
        }
    }
}






### --- MATCH HTTP REQUESTS --- ###

### GET BY MATCH ID 5bf7140e-e782-11ec-8fea-0242ac120002
GET {{host}}/scoretrackr/match/5bf7140e-e782-11ec-8fea-0242ac120002 HTTP/1.1

### ADD MATCH
POST {{host}}/scoretrackr/match HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}}

{
  "matchId": "e0bdb29c-efed-11ec-8ea0-0242ac120002",
  "round": {
    "roundId": "d8cdc288-dfb8-11ec-9d64-0242ac120002"
  },
  "scoringType": {
    "scoringTypeId": "d5ccbb0c-dfb8-11ec-9d64-0242ac120002",
    "name": "MATCH"
  },
  "matchFormat": {
    "matchFormatId": "9119dabe-e781-11ec-8fea-0242ac120002",
    "name": "INDIVIDUAL"
  },
  "matchType": {
    "matchTypeId": "99e5669a-e781-11ec-8fea-0242ac120002",
    "name": "BEST BALL"
  }
}

### DELETE MATCH BY ID
DELETE {{host}}/scoretrackr/match/e0bdb29c-efed-11ec-8ea0-0242ac120002 HTTP/1.1
Authorization: Bearer {{jwt}}






### --- MATCH FORMAT HTTP REQUESTS --- ###
GET {{host}}/scoretrackr/matchFormat HTTP/1.1






### --- NINE HTTP REQUESTS --- ###

### GET BY NINE ID 7cd3871a-dfb8-11ec-9d64-0242ac120002
GET {{host}}/scoretrackr/nine/nineId/7cd3871a-dfb8-11ec-9d64-0242ac120002 HTTP/1.1

### GET BY COURSE ID 79c2efca-dfb8-11ec-9d64-0242ac120002
GET {{host}}/scoretrackr/nine/courseId/79c2efca-dfb8-11ec-9d64-0242ac120002 HTTP/1.1

### ADD FRONT NINE TO HILAMAN
POST {{host}}/scoretrackr/nine HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}}

{
  "nineId": "f227dda2-dfce-11ec-9d64-0242ac120002",
  "name": "Front 9",
  "course": {
    "courseId": "fd844c1e-dfcc-11ec-9d64-0242ac120002",
    "name": "Hilaman Golf Course",
    "address": "2737 N Blair Stone Rd",
    "city": "Tallahassee",
    "state": "FL",
    "zipCode": "32301",
    "phoneNumber": "(850) 891-2560",
    "email": "adminUpdated@scoretrackr.com",
    "rating": 90.0,
    "slope": 115.0
  }
}






### --- ROUND HTTP REQUESTS --- ###

### GET BY ROUND ID d8cdc288-dfb8-11ec-9d64-0242ac120002
GET {{host}}/scoretrackr/round/d8cdc288-dfb8-11ec-9d64-0242ac120002 HTTP/1.1

### CREATE ROUND OF STROKE PLAY
POST {{host}}/scoretrackr/round HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}}

{
  "roundId": "c4b2a144-dfcf-11ec-9d64-0242ac120002",
  "roundType": {
    "roundTypeId": "d341e34e-dfb8-11ec-9d64-0242ac120002",
    "name": "STROKE"
  }
}

### CHANGE ROUND WITH ROUND ID 2 TO MATCH PLAY
PUT {{host}}/scoretrackr/round/2 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}}

{
  "roundId": "c4b2a144-dfcf-11ec-9d64-0242ac120002",
  "roundType": {
    "roundTypeId": "d5ccbb0c-dfb8-11ec-9d64-0242ac120002",
    "name": "MATCH"
  }
}






### --- ROUND TYPE HTTP REQUESTS --- ###

### GET ALL ROUND TYPES
GET {{host}}/scoretrackr/roundtype HTTP/1.1

### ADD NASSAU ROUND TYPE
POST {{host}}/scoretrackr/roundtype HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}}

  {
    "name": "NASSAU"
  }